# This is a TOML document.

title = "TOML Example for EasyMonAlerts"

[owner]
name = "Victoria Fantasy"
emails = [
    "me@vika.space",
]

[period]
minutes = 1

# Urls for ping

[servers]

    [servers.localhost]
    schemes = [
        "http",
        "https"
    ]
    host = "localhost"
    ports = [ 8080, 8001, 8002 ]

    [servers.friendly_name4]
    schemes = ["https"]
    host = "google.com"
    ports = [ 80, 443 ]

    [servers.friendly_name5]
    schemes = ["https"]
    host = "vika.space"
    ports = [ 80, 443 ]
