# This is a TOML document.

title = "TOML Example for EasyMonAlerts"

[owner]
name = "Victoria Fantasy"
emails = [
    "me@vika.space",
    "vi@umc8.ru"
]

[period]
minutes = 5


# Urls for ping

[servers]

    [servers.friendly_name1]
    protocols = [
        "http",
        "https"
    ]
    hostname = "localhost"
    ip = "192.168.1.1"
    ports = [ 8080, 8001, 8002 ]

    [servers.friendly_name2]
    protocols = ["http"]
    hostname = "localhost"
    ip = "192.168.1.1"
    ports = [ 8080, 80, 81 ]

    [servers.friendly_name3]
    ip = "192.168.1.1"
    ports = [ 8001, 8001, 8002 ]

    [servers.friendly_name4]
    protocols = ["https"]
    hostname = "google.com"
    ports = [ 80, 443 ]

    [servers.friendly_name5]
    protocols = ["https"]
    hostname = "vika.space"
    ports = [ 80, 443 ]
