# This is a TOML document.

title = "TOML Example for EasyMonAlerts"

[owner]
name = "Victoria Fantasy"
emails = [
    "me@vika.space",
    "vi@umc8.ru"
]

[period]
minutes = 5


# Urls for ping

[servers]

    [servers.friendly_name4]
    protocols = ["https"]
    hostname = "google.com"
    ports = [ 443 ]

    [servers.friendly_name5]
    protocols = ["https"]
    hostname = "vika.space"
    ports = [ 443 ]
