# This is a TOML document.

title = "TOML Example for EasyMonAlerts"

[owner]
name = "Victoria Fantasy"
emails = [
    "me@vika.space",
]

[period]
minutes = 5

# Urls for ping

[servers]

    [servers.Google]
    host = "google.com"
    ports = [ 443 ]

    [servers.Yandex]
    host = "yandex.ru"
    schemes = ["https"]
