# This is a TOML document.

title = "TOML Example for EasyMonAlerts"

[owner]
name = "Victoria Fantasy"
emails = [
    "me@vika.space",
    "vi@umc8.ru"
]

[period]
minutes = 5

# Urls for ping

[servers]

    [servers.Google]
    host = "google.com"
    schemes = ["https"]
    ports = [ 443 ]

    [servers.VikaSpace]
    host = "vika.space"
    schemes = ["https"]
    ports = [ 443 ]
